### PR TITLE
Update to support PHPStan 0.9

### PR DESCRIPTION
**Pull request by grantlucas**
[Version 0.9 of PHPStan](https://github.com/phpstan/phpstan/releases/tag/0.9) included a number of BC breaks. These changes update it to get in line with the latest major version, `0.9`.

### CODE REVIEW

**Comment by silbinarywolf** [comment]
@grantlucas Awesome!
I'll have this reviewed and most likely merged by the 23rd at the latest.

**Comment by grantlucas** [comment]
@silbinarywolf Thanks! Would it be possible to get a new release tagged?

**Comment by silbinarywolf** [comment]
@grantlucas Hoping to do so in the next few days. I want to fix the incorrect documentation + put in my ClassConst fixes in:
https://github.com/silbinarywolf/silverstripe-phpstan/tree/dev-fix-chaining

**Comment by silbinarywolf** [comment]
@grantlucas Actually for your convenience, I'll just tag it with 0.2 now. Will tag 0.3 in a couple of days :)

**Comment by grantlucas** [comment]
Thanks! Looking forward to future changes. We've *just* started using PHPStan, and still have a lot of code to get through to clean up, so we'll be making good use of your integration and making PRs for any issues we can

**Pull request merged**
